server:
  port: 10000
spring:
  application:
    name: kcjs-cloud-mq-consumer
  config:
    server-addr: localhost:8848
    import:
      - nacos:kcjs-cloud-mq-consumer.yaml?refreshEnabled=true
      - nacos:kcjs-cloud-common.yaml?refreshEnabled=true
      - nacos:seata.yaml