version: '3.8'
services:
  elasticsearch:
    image: elasticsearch:7.17.9
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      -  /Users/jyun4/docker/elasticsearch/data:/usr/share/elasticsearch/data   # 持久化数据目录（可选）
    ports:
      - "9200:9200"
    networks:
      - skywalking-net

  kibana:
    image: kibana:7.17.9
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - skywalking-net

  oap:
    image: apache/skywalking-oap-server:9.4.0
    container_name: oap
    environment:
      - SW_STORAGE=elasticsearch
      - SW_STORAGE_ES_CLUSTER_NODES=elasticsearch:9200
    ports:
      - "11800:11800"
      - "12800:12800"
    depends_on:
      - elasticsearch
    networks:
      - skywalking-net

  ui:
    image: apache/skywalking-ui:9.4.0
    container_name: skywalking-ui
    environment:
      - SW_OAP_ADDRESS=http://oap:12800
    ports:
      - "8888:8080"
    depends_on:
      - oap
    networks:
      - skywalking-net

networks:
  skywalking-net:
    name: skywalking-net
    driver: bridge