sentinelServersConfig:
  sentinelAddresses:
    - "redis://localhost:26379"
    - "redis://localhost:26380"
    - "redis://localhost:26381"
  masterName: redis-master
  database: 0
  password: 123456789