server:
  port: 8080
spring:
  application:
    name: kcjs-cloud-boot-gateway
  cloud:
    gateway:
      routes:
        - id: kcjs-cloud-dubbo-consumer
          uri: lb://kcjs-cloud-dubbo-consumer
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8000
        port: 8719
      datasource:
        gw-flow:
          nacos:
            server-addr: localhost:8848
            data-id: sentinel-gateway-flow-rules
            group-id: DEFAULT_GROUP
            rule-type: gw-flow
        gw-api:
          nacos:
            server-addr: localhost:8848
            data-id: sentinel-gateway-api-group
            group-id: DEFAULT_GROUP
            rule-type: gw-api-group
      eager: true
  config:
    import:
      - nacos:kcjs-cloud-boot-gateway.yaml?refreshEnabled=true
      - nacos:kcjs-cloud-common.yaml?refreshEnabled=true


management:
  endpoints:
    web:
      exposure:
        include: "routes,gateway,health,info,sentinel"


jwt:
  secret: zEPgB5gSZQq2QXD7N+r7A87wb3tOUYr0ia7uLdqRnYXpazJ9vZxDObVOgThN66l9lnaSMIo+BR1uqbeA7jh/Ow==