server:
  port: 8080
spring:
  application:
    name: kcjs-cloud-boot-gateway
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
      eager: true
    nacos:
      discovery:
        server-addr: localhost:8848
  config:
    import:
      - nacos:kcjs-cloud-boot-gateway.yaml?refreshEnabled=true
      - nacos:kcjs-cloud-common.yaml?refreshEnabled=true
